# execute
#      mvn exec:exec -Dconfig=bioqa.default-mysql-test@internal
# to test the pipeline

configuration:
  name: default-mysql-test
  author: ziy

persistence-provider:
  inherit: bioqa.persistence.peace-persistence-provider

collection-reader:
  inherit: bioqa.collection.decorated-fs-collection-reader-06
  dataset: TRECGEN06
  file: /input/trecgen06.txt

pipeline:
  - inherit: jdbc.cse.phase
    name: keyterm-extractor
    options: |
      - inherit: bioqa.keyterm.default

  - inherit: jdbc.cse.phase
    name: retrieval-strategist
    options: |
      - inherit: bioqa.retrieval.default@internal

  - inherit: jdbc.cse.phase
    name: passage-extractor
    options: |
      - inherit: bioqa.ie.default@internal

  - inherit: jdbc.eval.retrieval-aggregator-consumer
  - inherit: bioqa.eval.passage-map-aggregator-consumer

post-process:
  - inherit: jdbc.eval.retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
  - inherit: bioqa.eval.passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: bioqa.report.map-report-component
