configuration:
  name: generate-retrieval-ie-backup
  author: ziy

persistence-provider:
  inherit: bioqa.persistence.peace-persistence-provider

collection-reader:
  inherit: bioqa.collection.decorated-fs-collection-reader-06
  dataset: TRECGEN06
  file: /input/trecgen06.txt

pipeline:
  - inherit: jdbc.cse.phase
    name: keyterm-extractor
    options: |
      - inherit: bioqa.keyterm.default

  - inherit: jdbc.cse.phase
    name: pos-tagger
    options: |
      - inherit: bioqa.keyterm.pos.lingpipe-hmm

  - inherit: jdbc.cse.phase
    name: name-entity-recognizer
    options: |
      - inherit: bioqa.keyterm.ner.lingpipe

  - inherit: jdbc.cse.phase
    name: keyterm-restore
    options: |
      - inherit: bioqa.keyterm.io.restore

  - inherit: jdbc.cse.phase
    name: retrieval-strategist
    options: |
      - inherit: bioqa.retrieval.indri

  - inherit: jdbc.cse.phase
    name: retrieval-backup
    options: |
      - inherit: bioqa.retrieval.io.backup

  - inherit: jdbc.cse.phase
    name: passage-extractor
    options: |
      - inherit: bioqa.ie.indri-legalspan
  
  - inherit: jdbc.cse.phase
    name: ie-backup
    options: |
      - inherit: bioqa.ie.io.backup

  - inherit: jdbc.eval.retrieval-aggregator-consumer
  - inherit: bioqa.eval.passage-map-aggregator-consumer

post-process:
  - inherit: jdbc.eval.retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
  - inherit: bioqa.eval.passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: bioqa.report.map-report-component
